import 'normalize.css';
import '../../static/styles/main.scss';
import './index.scss';
// components;
import '../../components/user/user.scss';
import '../../components/socials/socials.scss';
import '../../components/nav_list/nav_list.scss';
// media
import '../../static/styles/layout/settingsMedia.scss';
