import 'normalize.css';
import '../../static/styles/main.scss';
import '../../static/styles/base.scss';
import './portfolio.scss';
// components
import '../../components/socials/socials.scss';
import '../../components/header/header.scss';
import '../../components/footer/footer.scss';
import '../../components/nav_list/nav_list.scss';
import '../../components/user/user.scss';
import '../../components/triangles/triangles.scss';
import '../../components/slider/slider.scss';
